apiVersion: apps/v1
kind: Deployment
metadata:
  name: teams-api
  labels:
    app: teams-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teams-api
  template:
    metadata:
      labels:
        app: teams-api
    spec:
      containers:
      - name: teams-api
        image: olivercodes01/teams-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: teams-api-service
spec:
  selector:
    app: teams-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teams-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: teams-api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: teams-api-service
            port:
              number: 80
