apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CodeCoverageSimple
metadata:
  name: enforce-code-coverage-simple
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces: ["default", "production", "staging"]
  parameters:
    minimumCoverage: 80
    coverageData:
      a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0: 85
      b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0a1: 72
      c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0a1b2: 91
      d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0a1b2c3: 67
      e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0a1b2c3d4: 88
