apiVersion: constraints.gatekeeper.sh/v1beta1
kind: VulnerabilityScan
metadata:
  name: enforce-vulnerability-scanning
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces: ["default", "production", "staging"]
  parameters:
    maxCriticalCVEs: 0
    maxHighCVEs: 3
    allowedImages:
      - "registry.k8s.io/"
      - "gcr.io/distroless/"
    vulnerabilityData:
      "nginx":
        critical: 0
        high: 1
        medium: 5
        low: 12
      "httpd":
        critical: 2
        high: 4
        medium: 8
        low: 15
      "node":
        critical: 0
        high: 6
        medium: 12
        low: 20
      "redis":
        critical: 0
        high: 0
        medium: 2
        low: 8
      "postgres":
        critical: 0
        high: 2
        medium: 7
        low: 18
      "ubuntu":
        critical: 3
        high: 8
        medium: 25
        low: 45
